[[HELICS]]
arch = "aarch64"
git-tree-sha1 = "1b2bc965bc2e1c589226b2637a25da47264f2115"
os = "macos"

    [[HELICS.download]]
    sha256 = "94be2a0669e433f4a87c9abbb8e7d1cb87fbd93dd95e53470ceda2ec8a9d7467"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.aarch64-apple-darwin.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad3c7f75440fe17e9f021be7c5c0546d59fd66e7"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "bf9c250252c224c2079144d5d6b860e1b8301942b9cacdf7b9389cf32a53c767"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d01599a4768dadb3d8ec6dceb66159b606354b2c"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "4147ee96a96609a497463d1a8024b7ef96ae91fb64e7745cb94f1eccb67fe019"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ec8086851835975ee27c1ce1e7fe2a15531b7a7"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "92d3e156b8ac8f44119334adcd947c1c3a5025c2092786c36877222a9280e0e7"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "822f6c1c5dcb405dff1c7955aa4958bf12bc51c8"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "14c6562f6f4679eb67c05aa9ddcbcf86f10833cf89794bc71f16cf193eeeaa23"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "629146851d735966b42e5ebf5c448dc38180306e"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "6c726a7aee1b1df0ab0d36614970cd362aa964489784709dc933fa929353985b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "599113b13521399019bbd271d9bbde97214dd73f"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c665413cb0e3c71ea1c6c0515cab458182e3772c40a408b9aee62d92d9759c1a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b4101eab33259db7128cce0aea407f094c4dfe5"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "980775f95a8ddffeaf145a9d8cd4653378a634eeaa70bc07dddd505b50c02f58"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "267cd5190a10afbd06041046697ab4fe6ef719d3"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5eb1b349b78df3671a8036868a847d9d552854a4254bd333f2b14ec3d3184556"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b8ed42979f738f45d5f11223d73e3bb3fde9493"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "45d6390d3d4ea1dfaf0731c57b5c7d6bd3408b10659a2dc4e9b7f18870283710"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "787a3eca452d0ea849aa6c76ce9fc817ffc85154"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "cb60a100c59dc03ce8cfba8959d56ac3f551b1bb62f50eccf23f81b1404fa8eb"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d66855516e834074d49b0de54c9eaba9ccb7943"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "b9f513ecc08fa1ea6ea3007e5a3428578e89d3d5d41fe220cb2b733b024d4991"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c40d8486731bf030dc8c58cbbe9ca5287ef6b502"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "98964084aed9a5ecdacd4b2188729e954af56a902270ad9bec793ca3acc4e766"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4150c7e7c8f0055790d15a9f26d9ff8cdfc6e82"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c3151de8433bd1a51f149b56262e7cf8e0ab23f7d2b07f40c13c9946b51be6d0"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c88ea729dedc0b6d47222e6ba9eb60a32871926"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "f82f5387c3de3381139b048386f56197b17ac077e8deee04754b3d3cd0a3148e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf3d106f835daefc8ab3a52615ce44b79d38681d"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "b80f00770102d8fc54b65ac38b90a4f4a73870e17176e961684eb12fa5e28c6b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "680562101c95f5767da01229fe9835522c6a13d5"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5ed0e8e266b49a75e15d29f9b519bd39afdda46cd2e3dd12cf6b67728e319a3f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0ac0bb054ee3566bebf4fc7df5423e6511282bf"
os = "windows"

    [[HELICS.download]]
    sha256 = "28a4a1fc3acbe9b0ebfe49d6a18027cdf0c0ea8da3179f3c363912c78a7ecd30"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3996f56ba27256c46b970380ab1bed32c444fdd"
os = "windows"

    [[HELICS.download]]
    sha256 = "157e5dde82bef84dc03bf7cc8194dcf35ed93898db17eea3a5c8f92bf78f8d5d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d303fca09370a02eff48fcab7ae9a72f4230655d"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "49bdfb6c4f474357f0c036d5852e6bb3a4defae8930e5e22d0188e71a7ebc27d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dfa691c6086530d438320210b3b772e49c32acb"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "888e6d171848dde5f2b9faa481287f84f60a921243290890d75b409c5d08a6d4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "0950acc8edd42371098c38402a5f57156bb167be"
os = "macos"

    [[HELICS.download]]
    sha256 = "076449bf3c391fab5e003b283a93c902d06ab96bb443da22ddda8a139f1974e9"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77c0dabed1abd6d9b8f1e073ee9ace3593331996"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "31c20dd6aabf75b2f7b1113899f025384ba4f444b03117a9bb7c1d842f4fac8e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75b6bbc0ad32768236ae33f30918bc6ba2c19087"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "b7639a79de1ea4c022e43beee33f27a31386ac9b975ee213da8c5df74a9a9823"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99a4126d3d9412114ce603881204545822ff92f2"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "9fb596f8cf433c4c6f0243415c1795b2306e292b5d46007cad46b98ec303cb43"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fb7974012fd9a015249a226786ccea1b1ec231b"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "dea3d032b2f5528622933521df312d06da36e96dd0642281a15129551828846f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "d79668fc56c846dda87eb5fb422ba17cb6d87247"
os = "freebsd"

    [[HELICS.download]]
    sha256 = "562e61ae8eb0adbe2cb1d6bb683bef3712517daff260bb54dd687762a67893f8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.x86_64-unknown-freebsd.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a870727412dbf6a5cd1a57dbc18404439e15ff08"
os = "windows"

    [[HELICS.download]]
    sha256 = "5dc2a162cda900baa53e61e11cdd12306111fc3e8cf4dafac3c17f0b45d04e6f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "957b713670ee781e711f0408d4de61eeadd518ca"
os = "windows"

    [[HELICS.download]]
    sha256 = "a1e4c75fdc94b043dbb43942cbe5351e49417bc82cbec54245030bf4870d74da"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.3.2+0/HELICS.v3.3.2.x86_64-w64-mingw32-cxx11.tar.gz"
