[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8d10949ebe50b63c310022c75293e71f6f8fed2"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "ca2052dd65991985aa3505ea7e99a9245e43886f609aa9691341baf9faf7bbb4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "545053911ad5c87cec2ac977e3fba2e63bbedccd"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "1541ae450f50a0c4d6893eb3a599cba76d08fa0017972189ea201d6983d46662"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56903bd1030115ab54e011f330219a9d841c23a1"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "8698be1ab44d85bc88c611972f56fb284fff22e1789d3ec78807ffc5a21c0566"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c77d91ac3b42a722002ec27b622bf5e01068c7e4"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "afc7722491798a9d8263213ff8babf2b80e880245e6d8a73c4602a4885b0d970"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aefe6d089927fd4810e56623f7edd3367b147689"
os = "macos"

    [[HELICS.download]]
    sha256 = "c01b25392a5c7fc03068b636f60378e01ee924bfe166004433ac5ffa15cacfe6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9c12bfdb0db2d286288818f90b2a1c49733fa80"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "ad6f6410099fbad7b6e3fd217fe4116d56a1733b8a11dbdf751b8d224cddfe2d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e36e9f73b1ba7a3a8b39c1a6d14bc791f1a2bee4"
os = "windows"

    [[HELICS.download]]
    sha256 = "b0c8ab01d3775f625b554eff870f41d70ea2295603a55e7fd4275c2f0fb0349b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b0ad2e948e9d9d5bd3dd314ecc75c991b8f0524"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "edee29d2a591e7e500f0d24fdcc5c9e7305d8bc7c7f1634f633597a26b72fc8d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72521b1543855cfdd83c3a737c97db398822aa04"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a1877b445ffc3fcaabd16fe836cb8a39ec3a7623c37fefa8a471675da7bddd75"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbb6b87399e2e7dad631f8ee3692a0e44143d08f"
os = "macos"

    [[HELICS.download]]
    sha256 = "32303d1c013cf2957c73b777c4f8107aec2062e1566f9e698aefedb293dd37b7"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aaf513c31ddf710d7dd9dda8a192087adf9a85c2"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "9ef4cc965ee7f121adde1ee84fb0418e420cc39a911c5409cb19db534a780c16"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb20c41c9257a256bcc8f34d8a4a5b1677147685"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "eb44dc376460c8b3de1d90b7018e1a8ef4dc164b07d707a3c179a6073bb720f7"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b1de4d2bf8b705c51aaecf5f964fb95c23fbf48"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "1a3229ce0047c878f6b0a29a814eadb771ad5fca09b3236ab38f1d28843c38da"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43a4ce8677286f71b168aa89675f798fc2a664af"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "0965f88407b8cffbe2b1abd654007c1c67e8ef81b964e33e4cbe8fa1daa4d0ff"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06e77ebe729f05d4ae58fb710abca5517c205898"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "5cdacedf816738708730b52c9fa1bdf4f916aa437fd5f091b386e790ec3c1a58"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb147a3d6c71cdb95add6523960faa9fdc9d7fd6"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "d8d07e2594d47005ad7639ff197918e2bb2c08496bc228152b75894062a75d5c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1ec7e6244ef2ca59bc54dadce8081e58e136879"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "9fad5bd7252b0050e4ecc5b8c08661643ff9ff89e0c185c7735412f1024e5554"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91a61f29a26d4bb1bd4d69c2609733cfc5ace5f1"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "de773868fb9df2b0cf9ebd6b4e8112014a56b6c269bcc92be75f031f80966918"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30e5ed1c8fb289f52f75b01b4351641d182f4e78"
os = "windows"

    [[HELICS.download]]
    sha256 = "6ed6ef7a582362262f33462c8b042f85fce1036e6092d725ef2986c68c5ce73f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c89ce78131198ef44705d62c562a0a8959524bd0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "4970b6f1da94095ab4bae51b1b3438c231df364514b237849b95e882905dbd6f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27f28fb2e4ce77c2c73b864c73f580397b18acab"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "e84445854ece15089678ff52f8ddb21eec4507b13029f928ee8483ec4fdd6471"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e473b0a5208cafd7623999aaaecae29d0751d824"
os = "windows"

    [[HELICS.download]]
    sha256 = "fd080c4665e3ce5494fc9af27b819e2b2f0060569682ab2ca169c017bbf122f0"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d69f89e3625d2cd353209fc714bfc4d4f5c4288"
os = "windows"

    [[HELICS.download]]
    sha256 = "3bae8a7baff42bbf258227e3466f545cb08705933c4e149f5e7fed57df14b4e7"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f309404fa0fb35f6085d8a42d20284f6e3157bd"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "fed8f337ea2187d0e115ebf93ed7d72a1ab6ccaf19b68f94266963f0c232a098"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.2+0/HELICS.v2.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
