[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b998563178577027689157f7bde55d53a46fb22"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "2fb76565f1aee5772fba873980d0b32bab3118aece036cc82416309e22cc6230"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce8fdfdfe6239eee543bb9d22685f9473ce22efb"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "1c719d351d1489324bf64844b9eef6cb62fec926b1184cb0230e857d0d38b18d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c3377801448b83ddb33a1aafdc75357e1029d21"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "89cf1486ed8193fbce3f997313ca3b2c3e015ddbeb98b1d6ac9a1cb3debca951"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "818cbff1f76be4c9c7451be27e4a25a6c2d56d2f"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "181953b6ad80f4f24846ecdbfd86361b94d94ca540cecd55b92ebf01eb54e619"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5ed376987d9ba27f50e806cfecdaab2874a1ff8"
os = "macos"

    [[HELICS.download]]
    sha256 = "79fc612e736508526374ea120eb4aaf8d0eb57f11a16d8dcee6f754433979686"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1014a97a225ae6b1928df0e43883a124c9050b7"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "174b0a433b1523b86c998c7921fda0515b6072c0b51695b10ccdb3919d895194"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d0d631379cc6bbdc2b8899f948cc7008426f8d9"
os = "windows"

    [[HELICS.download]]
    sha256 = "e9e20a7edff8055d895ff9ec6ac8e8cc3b4fa574fde86be8d706d807e7fb5d4a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "517d966d0797434c0962a0251b9c001234eadaa1"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "8a039a3fe565b1d8645fef6b6edbc5d456507279d57e3c004c2986f9878b5b61"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16fe867a55916c7059afe46e2e2968fb4c00c94c"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "0504f4a16767347794ec5d55dc792cac556903e54a6c9d352fa4dbf7e8ed43e2"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "744f3235abe154a147ebb4753c7baa4dd6f5cba4"
os = "macos"

    [[HELICS.download]]
    sha256 = "722044b92a1b3dab2536bf0d0e604ceed9bad142d243c315ac17211bebaccefa"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "022594775779bd630937f9ca0daa7457824b0fa8"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "eb87b12c7bb302a450cd0fa1977351d96f7cfe69720a1ad71b556456eb85d8e5"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbea1c3ddbff3e612df4948544ec50a31af910da"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "48e39483b2db729c2aecb07f98f3e21efca47889fa5ebca5ab4dcaebb216f27b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5fd0556a75996c8678a333228f66327b327a77b"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "05a2a43399e69811a3d86f2a94d04b0b32700834fc66a58592e8d8caaac9e878"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d2a0ac5b7119f4ad8df612eff0feed94fed382c"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "1f8eceb2d0444f861da94e58bb6e93e93cbaa19d9534037d7b247dca5ee1b853"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f581f5faf4f3e20d4002833490bab9005e93620"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "594765f4e5f5b1e77fb805e881fbf20282aa242d5406ec5e0a308bff394451b5"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b73bd73e18ff6205682cb2063ea18ec711ecb4fa"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "28b229d9a11d7fcafcbbdf745f7a4c5b0d888a8ec991dc3a5b7c3d3d12a5c91f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "769e69282ea212cae6717c275eba919c4c52d0e6"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "7414d9b2d15c651a66529a186177118183fdd286bdf181cb4e29002baaa2a474"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38a0b82ba9cb5a24a6e81d477c9b0382c0a95617"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "0ffe66f8d5c6d3409b9e490a04b456c7ddeb7ae5994c17b1b9e7c1f65b79acd8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d796732a5fdd6671eaf82985af3e1171e52d243d"
os = "windows"

    [[HELICS.download]]
    sha256 = "4eb3549cee80bff51eb9897bbca3f865b94e60bc7a496be96bd9b07804fc494a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b79bd2148a797cd70208bd6e94fd741525f58df0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "8482019da6722cd055ccc7aa6a59e98b641054815c7037445bc9eabdc0f74ee1"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d6c321a00a0085e116d544cf3df48df0e4b0fa8"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "849082a3c050ddc34801de4e10c0916acc8d64d77c926218fd92597aad7d01a4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb27ee3387272924965ca59530efd03c6210e209"
os = "windows"

    [[HELICS.download]]
    sha256 = "278468035f8f3256b5f7c0ae9c94a505f57635c532ec27072ae5fcc92b9e24d4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d2bd96ef3f88df85660ae5eda2a18b6f331ed68"
os = "windows"

    [[HELICS.download]]
    sha256 = "d59e6543e4071829bc158aee5d59c868a8f8400a3a6f37fb126de21e7a187082"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08c323e8cd87599e5adfd00b46cbbb8770e01e39"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c0206ee717e238e5b774dca356b23ca04a763c3ebe1414101a69ff1ebc5b1a75"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+0/HELICS.v2.4.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
