[[HELICS]]
arch = "aarch64"
git-tree-sha1 = "c8f5fc4cc248452b8889b85b730179d921c0b92a"
os = "macos"

    [[HELICS.download]]
    sha256 = "de4a07fd9ab77e3ef9a9711f5c27ac052614ff9f1addbee3051ef3b13a8fffb0"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.aarch64-apple-darwin.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4028db5dae92bdc084d9a42d853cd1adbb310bb6"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "280f9747421c763f0d7ea2eafb239f1bea32d0444c592010c1852ee90795ab05"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5693397e04386d779441635dbcdc4d023d415715"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "04c2478b2772e48cd2cc4914451df0abbdfc34a5af875d6640be6065e7417c8f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a225df131ed3c348fb2e716dedfdaeea269d2d37"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "067a0dc4a8b45e3194d6cddc0620e57794d0501f6d5b72c1d39750e343ab7fd2"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c679c7d270b4186caf14c2367e50de63c2795b39"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "78f3c1e2c4c1cc6ae4d1863f6fb058536f7fb8a16eab618bd325cab3bf363b01"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77c5be85e78ad5ef8bd6fb6f1cc08cf7d098427c"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "55b03e96983ee913635c196e966736e9acf6c16b56ba6451e4aebba208b0cb77"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcfec3a57ff29c2d6bc3f3ceb0ceb2a8d9c4a39a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "6ca73405548453ccbe0881573e34ad3d7f09954957502cfbe076c439bc066f66"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfe672456006ec55a8cec5df5991cb1f998b736d"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "ca409c3cf2766c46db5b0aeb084e0ad837251040cdbfd87b05ec98b04785fc2a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e03bd66c975cc479dd10e082d5c31b6521e84061"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a27e606cb63004c0631f387d3df3b617d5a095d0c5f6ac806cc6c4b58ca9fea1"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc44e733e030208c29a97eb69ebbe0d519d2341b"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "addff8095dff5d801b520387ab756c3cc0dfe2471382a4326dfaa8a409da9707"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d11e9a5799b27fb24c93412755455be44788e3b"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "19d1ac58a45911d24e9d720da12686732dbe06646b5efab13e0917b332f89d8a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9bb452ec731d84e2a3be45e2f485d56fcccf93e"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "0e6fee62da5a26e92639f4edd09e072ea9df121e24aad132686862a8f5f86b5c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1deb10485771a22cbfbc4aa562a69219bdcfc0e"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "7b6ccd81e5ebbbcb11f13532564c3065b3ebe6ddf395c123d40e0d93a4874cfd"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9376139219ca455c8cd31f2097d95c95d5ea9d7"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "aa26144e8b13fd863724219b6a2273030eddd6a37d2e5ed158b9d84bc4d0161a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a0e46b2cd6925211b9399f0a42d6467fd7f9378"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "41c92ed5994fb47ef3f2cbe6b19d145843afbf3a429691304578816b9bc3d4f7"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edba755cff546e9f016687fdcf62977dcba80e12"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "cadc1d73ce7590c5d898e46822727ca923c46d5d95de68085c21c99de9b92532"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aec72a90fbf8ebfa8271158c0a4c7aa922e2877b"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "6e5f9b6ff8dd66831ef58684fca86b0bb0ef7c558e89fd151ff12a6deac845a8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72d51979abea120e4733f235a523dc156354d616"
os = "windows"

    [[HELICS.download]]
    sha256 = "893e48455a30b002c13a22d899f062fd277f52c811d26549439eca3b7ae66e36"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcd79ee665ac824f5ccb33a1ee407032bd213ce9"
os = "windows"

    [[HELICS.download]]
    sha256 = "c123a415234426ad18cfec2444d68fe49c3694d037d68e5a6f22ed3c77cf5916"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cddeaad6cf9bff5b9c313a25dd265e285521be4"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "cfd005073f9bdfab016e38134f8882cb71ce97de0fb17d2554fa769716698d4b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cde022469f81b1274992b779bdd88e6d51d2a2d"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "0a8180229833dd4e38a2245b62acac3f514906f026e6c82695876609df5ac6b3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "4205ad75beadca9d6bf6aec4e0b9790ed0d2a0ee"
os = "macos"

    [[HELICS.download]]
    sha256 = "7b13c6e1cf679550db0e95ec84b82998deec3e831c47bf2bbd8139a814179565"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a747e77ae83192c18c60456e4c82475093d5d205"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c92b9c8426409efeb72a418589aeeca7db3ff4d09326a0846847bc3d1c089ae4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00631c9e47b747be51831d2c899b210df79578cd"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "3122bb54f59e5e8b32cb5b07b330c618cc2e309199f4bb3205c8aa3e3765f79c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "111e4cf22275a8c94b606cac6fbab04e93c243bf"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "0daf3a8fa6db69007c75d2d9d4360835d880d43593c6bf84508efb6a1b42c9b3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e2b597fac02bbf96e7504f8096d7848040df760"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "2f6465559d6aa40edf590c4fda40c0179c55578eb7c8f770ed3a5f8886965659"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "f9c98aa187596e651d30ef018c189de7117b45df"
os = "freebsd"

    [[HELICS.download]]
    sha256 = "e87041a92f08006830aae7aff0aa1b79a19abcd7ed7bec997f883220fc6aa808"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.x86_64-unknown-freebsd.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e11ad8459e4ab6df291ace6505d223af7ca4ad0"
os = "windows"

    [[HELICS.download]]
    sha256 = "a18806d979131a4d28a3792aaedcf3f9ecfb6b31f7c581c64b48fd781afbbce6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a4f0200887d7c5e78f19c67b225f8d657899e1a"
os = "windows"

    [[HELICS.download]]
    sha256 = "19808635098fec9633670bcb155607762bd0e0b9704e50ac1f5037df54862268"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.2+0/HELICS.v3.5.2.x86_64-w64-mingw32-cxx11.tar.gz"
