[[HELICS]]
arch = "aarch64"
git-tree-sha1 = "b199a05d88133a509f9f27ef4c1c1f08a7eba0e3"
os = "macos"

    [[HELICS.download]]
    sha256 = "507c4e0301f232e39e8a340fc21f3a1aec4a6f0880c5d014bd77435a93b44835"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.aarch64-apple-darwin.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33b7508b455711d387bf44a6d74e1fdaa25796e2"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "10cdd76acc63afd198a529dbe76687b01211a96c2b372da32401922de4d6635a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "889c73bdfec9d879a7705cd20d42717011c01d0a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "2fc390ae9763e60aecbb1442da007556563cf78388dbff07e75aead1a6141abc"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9c960389348a6ddde6a5ae92fd678dc91ac4c81"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "586b9571fa4dff3c56b5dc5e47ca77f38cbb1c1ac4f3f6fa1a088ab6cccfd1d8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "feb64d94165a23cd4d8269ee2b9a5c105044b54e"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5dac26b75612ca38e5baa3670e8deaeb3466a57e4a5e548bf13e891e2491df43"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e57d3b8dbba8737c710f4f3e5ea7f7d3dbcbb2e1"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "680a48472b9a728f1e52abad270944c7610d3113657030ace6c1d967f29158e4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d205c3aa0a82474efa0f35f4eb7de4c0173f4ab"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "eaaf7e68263afc365e846e21c51a9685a114d196a78a03e0853e1558e9231272"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3795c923d092b4b4bf5eb1d3f8ab0563e79dc322"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "647ba466037bad26c912004673b06a464a71fa44eea988f940e5ebe8ae3f2386"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f0804ccff4f674d24ea4e55a91634c11d22a57f"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "78eb516269fd3e72b96ec9927a40f19568eacfbdbac03781c9915ab679220dec"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a67baf286756db53c17f8c30c7a986a9fa8e379"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "53347d9a3b86053a5ebb23332f7192859cc6b71acc161c82f338b7fcaf2e3414"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db36cd8d99496ac3954c9c26c15fd8499de01e15"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "d853c953cb0d0420f6c799e052f6a69a6ec481a2b4f2371d74e4cf5b1aafb871"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb2eec250a9495f5ad4c3b8830bc1c37d8492138"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "0e2c96362caf1dba3a932336f5e1eb352bd6fd19a998ed236c4bd5bd2dcd85a4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf9348ef1b541dfd5f528178c84d4709146b9002"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "064137e224a606774aab1333574608001e81af967a3c742855645927af37f357"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2240c7efa64b3840dbec25a6cb99dc74eb1333d2"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "4a83acdd5d7e577f9cc128642db1f0d8ecc5647500f568c959ef8d3698a3edd8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7e49b85d359747c40fd4f2acc697f8c4aeeba8a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "8ec4c97370b9c7c33126872a7762bfa3588b3ae2f7df30eb0ba6c89cd113ef71"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ffc2151784d196e8f86f7c8a1c59e9189e958d4"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "f3892ae3f125ca3d72ff9119d40a1d75209601bc31c412904e5d2d8862845e74"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adcc747dac0585803613e34158fe498c080250a7"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5a50edac660827dc20e2e55b0adb11ee8473b8265605eea492426d747b356e8f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20c61e1e1115a2e16003b7dba9755087ec22dd62"
os = "windows"

    [[HELICS.download]]
    sha256 = "309d1415c398385f98579c3d91adee6e01d62cad92cfacd2602a455fe06f982f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ec53c8c396718b42439e318d91e82b120340515"
os = "windows"

    [[HELICS.download]]
    sha256 = "65d5b05d0ac0a39c84b06f2122e78ae0ffa9c9de0ef0886bfd111773d9844133"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "246dd48a04d92c531704396159c476b7c8c2b110"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "7914a55a1b7b2d7c238498cf78671bdfebce85ab2a25a9706d2944a82a823472"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abc3ffaef07148dcfe379139f8f96d9472e14643"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "1876d265a0970f589327d82e9b6b80961a4df3792e93104cbb1ab546de254aac"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "b3ca7ed6617e2b8150265b2f85edafa561b8c1bd"
os = "macos"

    [[HELICS.download]]
    sha256 = "d22a00e23aac9671646bc02ccb5a0a8136d111239b2b28490cca5cf693a7da14"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "548bcab8d13bebca726a7f32625a21ecf164866a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "1c849c546eef0a0c3414577a653158070e0042a2dcc46386e2cc6e5fbda2b160"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "937fcbe1c3c2ce832b2ddb5e44c8fc13b83fb22f"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "31a96b8aef8ffe3226537fb25cb4c68a5d6c47d3b6e7b5ee06016efe667b419a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b41c40b393d067a90bdd8b1081a4e05ae73dddca"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a9e0744e7524348f3d1129c42c546fb24c84576cf26b7c44a4cff80908f2c558"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "086dcc7406902e4c103e146befb1865c76405f26"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "c9dc6a44de055810d51242cad8c4308469b45a4fb9a20373c1b021436027b6e8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "8685c80b3c397e9c96a98198c213eb8fb4667335"
os = "freebsd"

    [[HELICS.download]]
    sha256 = "cd4a8836f60d6b36adb47467d6a06bad6e2419526c3d608ae9751f3b91d97a80"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.x86_64-unknown-freebsd.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0f65e843941f70b7b26521b9b92915450765d3e"
os = "windows"

    [[HELICS.download]]
    sha256 = "975afcd73051355deb8539c300f28f700a8ef8f0c659b9edbac2457d5be3f76a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d15ef8d2d65f4760a60bc4965d35c54a9e37827"
os = "windows"

    [[HELICS.download]]
    sha256 = "235374629a118b99962d9f93cebd9cad05ce6d24f208f7acb1992a29795bdf5d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.1+0/HELICS.v3.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
