[[HELICS]]
arch = "aarch64"
git-tree-sha1 = "b6f5af17c94754827d8d15d76a2b704c299dac6e"
os = "macos"

    [[HELICS.download]]
    sha256 = "f6440f20ed6c3b3e24fa5a501592861360ec8c6b61533befba2c48717adf1ed4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.aarch64-apple-darwin.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eac90e0d0bae437b6edee597c71dc44724c4ccd0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "1406c845ee6381690b49111edab57185473fdace9ed9289d001256b5852d3a9a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "044dbae4c533961f1058f4805932f88347861390"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "89ccddf4dbf8563148c509efb6e911fec6148f0c763d2f4134a6d3a84a2cfe47"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e353bd601f8b7d482b9487a7e18332ef9dac026"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "b903a068895d401bdf7ca1786d30267151b2b73cc878b684ed142a89819d1b99"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "749b858e59f79d0ac9005ac72fa5fb72c3d77203"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a94cbf444f005d5ddb2487387a412f728103d96af70d07ecf975d59d5bbdb755"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "223f5fc6925ee7ec3561c593785f4c3debe056ed"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "e0cde7f40417aa4a707bdc4065e4c6d9d0809ed7461a6c37ba6df4906278a588"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "861f13e2a980017973e97aaff368f24ab214e37e"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "3946906db2dcfff5c63d24d877e8dcf87a5216aa6fd20cd82655dda79bf610d3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84dc242fb0f55fd912a3375dddc6163730dc56a8"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "bda93857685f3c2ffdc67af1a37e8f35548fa269731657fe27272157f512dd83"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b809faed9fa3f64c327cb4a67687b6ac63c401f8"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "f34a4557fe034e3fbbb04dc15722d3db76c9fa2cf53423557a848034a8bda1fa"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccd626242c8881edbef2a8218c1dd268d5b3889a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "05edfca2567875f9bd7ea79494af075b1c7ae4d56d8b507cf2ddecb9b06e6cdb"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ca04ad9dcb125dd764fa18b15a3d3cd8d7a561f"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "9ef44e24bc0aba9c90e9e22e838e6d013f54e2c332a0a161f5194560528c3c18"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cb54d249a59fc809f8e36e79d88eb472a5a3bc1"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "2228076bbb7500a2d03746dae6f5e1f207405db5180a414a0ccec4479fd4d464"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bb1b4bdae4c42e4c7ee15478064d771270fa0e1"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "710ae2264f9dbd037021e8d755ad16ebbd8adc4e122d7c009e2f3d037f305219"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da4b1a34e597dd48ef90b890386b001e890b5a5f"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "35f9a2dbea13cde971202323d4d0fd17b5f644c55731d2caf44374378d7ff3b9"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "840b984a7ed1f4adc37e6d8579b3770aaeac41c0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "089733c3c08484813aff2102d55c6086d4d9f551215dace297b8cb8c913d8c90"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "204966e1aa24c25eba55d69c39d605983c3b73ff"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "f61edc45686c66f8eaec2d61956306536ccaa6e77e54e5a394efd77f01030b0b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c19aaa4708bb0f893f948db76e6cac4c946ad03a"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "0396f8156a90d65ac0325979124e52e6d60faf767ab59e431a30de7d79535af3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e529cfa65d1a15482dbcbdbff67b9c45cf225ff"
os = "windows"

    [[HELICS.download]]
    sha256 = "8406d4ea9f451d3bb46dba4d00aa59e20b083701599234a41ab9f94299cf19a7"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3e4c42e327b9bc3ec5aff73c37cfa03a083285b"
os = "windows"

    [[HELICS.download]]
    sha256 = "0fac8d0cabcdbd28ee70ce72ae68fae6cc3a9a712beee4ce0442c812bfd25f68"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45b2bae0898dfba549a5dcf5f300f062ff43efbc"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "421d13cfa11e58ca8cde3688c1c068e28e1d2859145a8d0b58a6a89c4268cb9f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b7054803d89c38301233fcda7b10e3fdc98c50c"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "5991a7c269638a579b8f801c550a08da41a13eaea56c2c2d7e83c4023777f1c7"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "314905c6877d087809329108073f3ac7267d170b"
os = "macos"

    [[HELICS.download]]
    sha256 = "815543c6961a98ddaede81160992c12d510c04d1a7c29875066f34fed2252b2e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4de79d0e10cd2d6bc185c9fa7aa61b50cd370acf"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c991f0bde5cb869cdd1e83575c0f5ad1c82ef4812b2c28a520dda76c9eb72afc"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8cbde7db6cd16ab1a826176ae904b792cc30b81"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "f5e2997432473fc05d66c771a0d55c07ffa5efe05c1326271a6906b99112cf7e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7802a5ad9f7d977ff93eae589b11f4446824838"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "2d5a6a737e148d01934febb30964c7cd51db58fc83a137040394c2d8348235b1"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b9ed6e37f24c24e22e54c1a9b6c584e4e433afd"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "8d2efe4d994f4fa1cbd54fb2d8d0ba6fbd517ab4c7c2b67987be59a3202862fa"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33c9c35975006b7c176d0e8c6b3ef18c88ed870d"
os = "windows"

    [[HELICS.download]]
    sha256 = "07bf48038947a6e60c2583b3f97106b93e1d6c6c9c8c0e32653fc6a730f96638"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d8daab4fc6409e73d8ab41be9dee378f93c3506"
os = "windows"

    [[HELICS.download]]
    sha256 = "18885a783a47a037eb801f54f54ed02ce308177bc891924c154964e7bdc7d008"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.8.1+0/HELICS.v2.8.1.x86_64-w64-mingw32-cxx11.tar.gz"
