[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73e0c8e357749cc421acfadc58ab25c470ed5776"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "30e50af0677d7c7453612ccf59fa7eaac74be0f63e07244f9b3cda934a502410"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "247ae91388d7069987fec22e48d44726b4d657ff"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "2ff7f9b55c0ec25862b0387c1c7d37ee9ee6fd4ef5b6f179c9a5d759c205f9b0"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca210f88c37a9f06ced3184c3e8ca90b7fd01530"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "30237f8c8ee32dfa0b02b5f41c7c6db3f21046bee9fdd0f3515c862d21837f43"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db8ccf6a2e82dd882d0f300d9d821c04211f0577"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "d53f0b299c1dca3d31d3ca551eb4961aabd9c6232bc0c9b0dea5fe641c8d49bb"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b203dab34bab5bbe08822e8c28da902882c4c868"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "4e95791ebc4e621447f54368dc13b31224bba84129c6e784643368236f9af415"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7419e74bbb95a0ffd044b076d5dee2ad49343d09"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "1a72bb3cec239ee062ba85443c496fda5b15db5ed3932b7cb44b3d1f95cfd062"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0629350f48339a3ebbf7957f3d1a87ead7b628aa"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "c158c46098e6cd79b360a12fb8f4b00f7ffefebff33f3bd3d1a7fa92c564f081"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1378d3225e59be3f3371c606a8427e8585ae541a"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "62d270f895c0d06abfdd4a9102d7e0a53e2f8e01a0c3ef81e767813103fea827"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e252a5fc507e86b2c6a3fcc7d3cfdb24ee2a78e"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "6c3b99ed36d44553f2211b010bd12bd1a6db19bb1946bb2ee8fe8bd2c27a1a43"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54ecd6aa5ddd0fc0e09307f6cd0a6ccd8bb6c3c9"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "0f795a657995e8e9f8a43f3ca9c84af43c42b5e7189f20d18ab91af7c6cd752c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d77bfdb18c1e6c24e0a61ada18569b762246c996"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a275f5218175a98cf6d62cae83a5a51832ee24a8c9a54ad228c984653009dc5c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7eb43afd349b12868ea8ba1eef54603bd0af260f"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "6cd9a208bd9a60e706383c0cb41e3c41ea02408f458272bd38a5607cb1dd4b5b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4865346635e73d241b7f6ee7513ac82dc86eea8"
os = "windows"

    [[HELICS.download]]
    sha256 = "074e195e1572a73ee06dcda08db304460decb818906334fb15a19547bb758617"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a9e1e574c625921afafa0d1e5bb11d06cb6fcc8"
os = "windows"

    [[HELICS.download]]
    sha256 = "4c4899a43133fb82cef2d0cbb702d6d3b8cf6913a2e1eecb29540a3c95b46c30"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6328c801d1f8a88b80786a52cf020240abf3522"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "5ca9ba4379a0a21d92c5e6a5cf6be54fc9f41960c56e0610ed3c21b88d03c948"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0ecdb23fad64c2076d216700d9e72b81489bc27"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "aa8fdd5986ef01991f5c6fd61ceccb7dc2d656524b9228eadb3b922ff61eecee"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "edd8aeec115d5e734ba769bd1cf5ed0d2a66e60b"
os = "macos"

    [[HELICS.download]]
    sha256 = "b36ce3c31c2dcf80505f63f1440a37fe507e5e9aecface30d6fde07964872874"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a35aac4a4f3214864307b79b3e7e87fac3c918e"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "7657c529ae5c2bde545d64088eb01e56fc831ed08ca12dd4d7296162195ee5e5"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6594bc1b2a1fa54229e9c4dddbd15641fe4f6377"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "d99951f836bf160a6f6a96c588435e640861f4448beccc1d7ec8ca1d58c3af80"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "047e576b7d9068106e33a9d97efd3c62af05a664"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "343f37a56f243d39167024a36c52da5b328b3ba74cea37308b830db2b3b24e38"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d02635317c811bb34fb210fad197c1f6a026aad2"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "ae13e0060bdc3de2d76e41355b9d646bc04ce3d6c4f95eeeabc4909dddb0c320"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfcb58feefa077f0e28ee8c1987eaf8923e7e3de"
os = "windows"

    [[HELICS.download]]
    sha256 = "b6d3bb76030af1853f104ed8d73c0fecdc1896f745493dcf3cfb8b45ffa46110"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64eb5ce53bfb358090d8708652b7ddcc6e0d2925"
os = "windows"

    [[HELICS.download]]
    sha256 = "4dd36de4ce415e757665e60e4b918dfe9784146916e0c636ac6cc52383f984c8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.1+0/HELICS.v2.7.1.x86_64-w64-mingw32-cxx11.tar.gz"
