[[HELICS]]
arch = "aarch64"
git-tree-sha1 = "6e5cc7f9db56dd5a33e1ce201b1a40d2bf60d739"
os = "macos"

    [[HELICS.download]]
    sha256 = "df574c0434577a219fc4ca8b6a98e0934522788fbd05acff962ce0b9c7402f29"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.aarch64-apple-darwin.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "563e04995b0924b5954fd6d9de2a897ed1e00fd2"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "f8b9724511c7f0fd33ed170bbaf5bc062b345ffc36debec48dd380ebfcb83918"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85e7f2e728a007f42841aea531c33f0916a6a706"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "0a4838f8e4057f9c1062dfe683a7479eb7419a437ce9e779d7ca879c8fc98a03"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de203ec0d21557cf156505da8c4f1b7a1d656ecd"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a51c2e5aaee9f04d8253dc31e3666d4b781e1f2f8da1fb5ab80df24f64e8ab4b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3b35b3df7012117d8a5bc2342ea6918b44b60a4"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "388106b4a48e0fd543701d81f0c57bb92faa7ab0b449e0718a87211a216739e2"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "611b051753ab21d745a3ab44f83278dc679925eb"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "7fa53d922d7c453c97e1e4f6f2139a13dea473d7ba5afd7fd15213fde01ccf61"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7e8609a33aecf4ae898e61403e4c654b198a0e2"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "84ef0bd8e3d7a8f864a36050ec20420529cb77f0e764738adb4d1a1ed1e7f408"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f0222ae12bf1ae49c1208a34d5193efaab86c93"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "c9e694762a2f02992631fe19d4d5ef423bb63bda777435bee2db349384e0b5ca"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2318162a2d597549b3ef7586bc2ed974aee23d44"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "cd919d95d58ace96dfbcf00dff21665331ab6cbaa58edb1499c98fff67454bc0"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44ade4518860d3046abbf15690d7b6fb57d95b97"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c956f7ad67cc71a5867f1c17152946a4a9d6d2ea4549ec8aeaa8464e1a7c50b6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7f29de925b6e49b13a360a44791b9b50309a33a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "37cb44ae3871afc33806fe35b6255ddf375b233f9a62cd72330d1ec41a75aa88"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3cadba12dc1eb3aa8502428377b660cf953dc5f"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "f722a673e6e991e6fc79f318d4391c451042d28f4e3b5b42617f5b05c1896ace"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3373e5e7775d1789b951f9ce58518a3f7cdea9be"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5fe1349f660c46fa04f4786f78937faf7b0bc1e4435e3a0fed750a6a17b843ad"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3ed900f48715b0e42b4177cafd7bef300142fce"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "b4bb9e78ce4fc17082e2d5db2d797010613ddcd08dfa09346a02b6d2769d9f08"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d1b595cee6a81fd4e0eae4765cd0de648621e63"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "61da261e20e88304aef6e1e74d9177ab714122614911dfde93a83fff1ec2477c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "186b33806a868896f7892f3465e11d81394aebea"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "75bbc327d18773cd32b2e49d1b3021127206cdc0216135e964eac616e4f0988d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "186b00fc9c63bd0537ec282621ff857b4e40857f"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "b114a47ad00ba2636e0d4bf28e1f9276a4cc2bb5cc026a3ef561c7572e1c0311"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3df8a32d5fc8b5aff510a0d8b77ef671a9ee4cb2"
os = "windows"

    [[HELICS.download]]
    sha256 = "1ed75ee0092af706763b7b235fa92fd2c224debf8e15b4306e696aafa5fe9c32"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c562a7d27ecdcb02048c7b06b38c96a56f9d1c64"
os = "windows"

    [[HELICS.download]]
    sha256 = "dd23d03fe3b0da31260fa6d3250c3f87ec563feca0867705bcf2b89eca655a7d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "240571a719b3f04d0507cbf14bdd0151a44b88c0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "f32c19ad0ac54bf2f4c4dd6b3838fcd9f814a69a74722920d8d54e8facfe72b2"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "978d63c7a48ff727a2700d3f4072da3bcf5b884e"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "84f3bb90791718227136ef55d27808106f69e21c265a19fa1b4e7f8d446c7f58"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "e995d6f88491e011cd84f2b2480acd35fa91cb7f"
os = "macos"

    [[HELICS.download]]
    sha256 = "8a6ec72ad8e302228b2dbc7d8bffd881fee316c1ed715c3d9bacf4473754e931"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50155503e52a05ee5b033f39c4d78062c2ec71a8"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "d898e8248317d52cae4862514b468ab41b259a7ad4d72b2d3d12f2dae86713c3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b6b06ba081335ab61c8166bcede874224146227"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c577aaeba0051cfd934c0a137ce70f7673fc8ee0cb059c75c0463b2a29fa3071"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1f1a5b0bf3798354ae4c49c4545b862d80c9ad3"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "23d661eeda707184560db86b7be88ad96b083a4d8a832324639f6850e8aa2000"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae1f66358a2034c50a8a375b6bba269e85b412ca"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "c1d0acfafc1c9001376358b932f3ec750e67fe80434c5f11dc535176bf6a04a4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "0a6ccb6b8a3dc94993578948f5243bb072c2337d"
os = "freebsd"

    [[HELICS.download]]
    sha256 = "810364babd1a8b9f86e829705389887f6cabb479dc7ac354fd1c47fbe56b1fcd"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.x86_64-unknown-freebsd.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3707e98ea99380242c02b05406f645700e7c37c"
os = "windows"

    [[HELICS.download]]
    sha256 = "fd25b38d2b1f97b317ca08b1f869e21e7905aaf5d3635b6fed3b8ac1aeac0443"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2037d1047938749e301146deafd71c2640d0bb29"
os = "windows"

    [[HELICS.download]]
    sha256 = "2170c9d321edbb21404393094b1ea94e4fa1399a2d3eed74b4c1406d1ff65e09"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.0+0/HELICS.v3.5.0.x86_64-w64-mingw32-cxx11.tar.gz"
