[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e009745708e758cda79e1fdaefe23cb7746cd80"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a4d9b1ab04b6f66c69729a7c610b36694e83828819ddb6d40efd1e3da4eecf5c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1c8364996ba4976e7e07a37d734e3e56ca3fc54"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "466132be1f5f7e88cc572fd82c6d580338f7969bb9eab0bfdfe547ab9839012c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b1c7c91da8f2c0858a526f756d7e5f724e8050e"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "01dc827f2219e1fa8a50c53b5a6bf5b8ad46971e742a14a0a576fe8820c1bb3e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5c0d8f8c973c7426f05723e8e6e297badfdcfeb"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "21fc4a03fc7eecaee35f1bf49a8c589f0833a23cb11dc63b203c6b3a8090be48"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75f19a8f508ec8e8ee4dfbaacb74fb38a154e47c"
os = "macos"

    [[HELICS.download]]
    sha256 = "3b1699c509b5c2f983ab1fe8ae4537fc9c56bf7452211f8c440c89b7ff926088"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bcded5383bceac52b16b4e4b82411ae94fe5ffc"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "872d39908fa0970b1f281ff6d8a473c0541bf13a21ccd86c9327971103b7cdcf"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6fcfc8a2d90a5d33ed3ccb9ad4cf04c7159c3771"
os = "windows"

    [[HELICS.download]]
    sha256 = "fcdeb624347088b5437ca52897cbf4ed73c8a6326b2a17589bf290c843b58d4e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e973fd15bd309454cf5b51dd45e7d29092ceeb94"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "437c4fefc44571c303e7269a20a31bdba6c6bdd0300114c5d47e8a37289e793f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39f0354de7f70d34a341cfc5825e2a83af177547"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "75a3667b88e0878ba3dbc976ed4bb048f5cd53a2890460e498cc1877fa832403"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f423dcc86d1867fc9ae9218202cff99f6247d70"
os = "macos"

    [[HELICS.download]]
    sha256 = "ea59ad544f525e736351ea56486075ed683fdb7c3a00c17ce5ed61abb178e033"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e02f525c3958747819df9e2c5e41247b9a3fd527"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "68fc1da9df6da49802766990e182cbf75775c96ab70a38342926034b3e40dca3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae6aca98f0a642f846ca702c96fa0344cbb38b99"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "9997dda039b5fe112283364b9a865064f54af479c2dbf4eb27c61260741768c3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d031a5b49a0d53ca053831bd1ef907de7a6a564a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "71b4391b7586c8212c62aeeb70ad91b7688118534afba6e2799dd13247f34ffb"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c23e81f6bfb56fbf16729b8fd422fd86fe2ad5f5"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "7d353064bb7f403d6128cd20aed26c05d789042dd89665a577fe052a4d6aae03"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dc4dc07b771e32a63a9bcfb2b42c28fcbbec8ee"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "7f16487d06358ddb3340b396ea0f11d387876d5f4a909e00df7fbcd50fc1936a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25d9fd306c1cc3f9f0b9b9175e35accd9b77a5e5"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "2f45e6e8755f7f9f349bc7a4375ced330729d06d2ad75b7834b8ee20ccb73986"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d43b1450b2eb9590beb0a61f43e5531c9a8fcd91"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c7026ac5cb01f60e72e669daa41d91035c12f46b8a925b13988bf62e64632bd2"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f433e21678f01a6e730819576f94a3ffa218267"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "2e930c89d77f9072d80904ed74ef907d442ea5fc4fe04e9e8894ebe5808ada0d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9daccff6fe1beaa80b801816bdae7c43a939724f"
os = "windows"

    [[HELICS.download]]
    sha256 = "f8a69a3fdcdaad748e02bafcf7ed981f020577483dcfd83a47cd45809e9c5936"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d638cc67e14bb2ff29341ce8f0b812c5d93e47c4"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "b706b94f93e59bfbacd61634cf4c3cb9e6f3f17e796f677bf2e168916e1e3f6b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e64200d23d20d14fb7f011cf5951bffa4fcf947"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "7d43623ed701a91700b0a679b497c02426dc43a4b018886024dcdc1eb9088368"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d08ceacc29522efd6ce5fbb7138b7edd43ccd23a"
os = "windows"

    [[HELICS.download]]
    sha256 = "fd8ec9ec868319f41641b348fd9e128827984c78443c1fc3300882717bf66c00"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7b817a6059f89d7d3fc9a7f9fa67cd41ebf5aa4"
os = "windows"

    [[HELICS.download]]
    sha256 = "e59640193526ed1fcb4feb55a51334dc2928db8367c89f4ba4473a930431e0a1"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63cefd7b03d6e7b5c32e5e70541e67052d34bea6"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "b6f76961900462ce1884523a5ced1167d17ba6148fddc4568523a57b36630ece"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.1+1/HELICS.v2.4.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
