[[HELICS]]
arch = "aarch64"
git-tree-sha1 = "6c02ba5dcca8b90b85255f3ca7598bf324e61cd4"
os = "macos"

    [[HELICS.download]]
    sha256 = "42a213e74c19355dee18fad2e9cfcebe98409eae43492a185f2f333c283a4adf"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.aarch64-apple-darwin.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d35d694e473cb88f56ba81dee6b43ffe9ef2efea"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "73088b3b058e7e4b047d805adcc9fcc7c54519214ce4cb8cb667b34d5a403825"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86199c33912b40487ce0d4f68aa6f5503058486a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "73bee0a476987869abe1db567197461951f92d4ba0db8a6cfaa95adbcd86bf7d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1824e5b817f5a58a09c57e16c440715b9c58c714"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "77bb6d6f13c53932b998ce4fde177287057d8fab50ad91e3aa514d84ebc06f10"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5564f01b439ad98bf9c7c99776be0e7e54494f0"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a076d7c2a49fc481054696e0e7c9418275307ac2e6754cc0d8d18caedc06319e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b415c9c56d956c4a2a99b8bd29a785190593aadf"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "43bed75aec3328ec8ba5d922cd442d03649c7cbc9a4abaae507e2bd7b1c60c0f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e3cfd037ac3d8541893b4a4f15e86c377b4fccf"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "d2b4592cf64e5793cbcd3e65cb8e4ef29ee81359ceb56ff2ec68d83eccfdf862"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d94f69640de7757fa80933fba6ede628dd95167"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "41f36162fe212d94bf71b0666378d8a12a2974648e18d252b53023d9a5b32bac"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "105e6a760577aaa6ca93bc9e4eb243d4b72d7d33"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "20f84aa77961609db5eecce8d54ce5b3af17a09b7a5f1d44858fe0ef96d1445b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cc3064928facae52b39baf98a7e40ad17fd84cc"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "f4b3c7ecd605deedbd7b1f084a041e6ac896e16c31391ca69f17b2a4b6b01bb6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9b5255d5a6f9dccdae3e43fc35abeb2430b409c"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "7183a0b55fe64880f22a6cfdfcb53b76eb6ed347bc006135e9a6e6de2e9faa93"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0965ea2cf49fa9276fd11882607341b59bea8fc6"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5980df55782f2ed10603414674ed6c63f4323737815f38607d690b5379f56b6e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34a4d7b5b791ac5d8a62347ba7e7d1ea95450cf8"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "ac8dead8bcd03c11d717a077f52bb7bdaa3f306ccd5bd00f459181742e21e245"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "790e9e8094795b0bd6679cbf6701982d5e5cb3ae"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "9d3ae5f21f1623108d1102fcf5a9c0ef018d6bc5f62da943f24545500cf8bd55"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69c6d1f2a25485bee8bc21184d1e68dca9b14458"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "b3583099cdd730f0ea1b28e4f620b9d0499a699f53a4f5866d5a413352c02040"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4176f19faf4e80cb09e07fd1250d72933d04f1e9"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "05b473e76f7247fa5920027db44e3fe8b8b2f0931ac5ad8e7770629c5d807fbe"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "431550a887f2354b8ca1ec767d37a0458f274127"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "805ae2c0f85d635480a496f6cb13e8720e1839d2b3dbeb82fc9c03a162473b62"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c70c0390a462ba9f398e505714e9af940c39d7b"
os = "windows"

    [[HELICS.download]]
    sha256 = "5b8848c2a84ba026a57328419e97721e51087e6a4613f54bfae7a59f4a20bb3f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "895d695739408eb99f3011824cbfdc19defe580e"
os = "windows"

    [[HELICS.download]]
    sha256 = "0576b802cac7dc43246c00d8cb66bd98321adfd251f0331e3ea1c1f89de4684d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b66a977bea3e62e9acf564d47b056ae75ef533e6"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "5cd3dd0bef64e1ce8e137bc155bc277f0c16a4477a05f83110a4ea9c1d19b09b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3bd1caa1924f0fe14495e49bec930106ddd026b"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "bd36b37641b2aacc3ce4adfb99fa9d5125d73b6875e74abae0767b30c0630a67"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "b437b7eef39cb1cae195f773bbcfe357f50cf579"
os = "macos"

    [[HELICS.download]]
    sha256 = "38cb04fae227e8cf5a377a5635ea65185814acece4d81447a01098c3259a72f9"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "667320fa222b6f8ff62241b7e2f3e89de4bafc46"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "8ddbd2efe028d0d47e4e757bd3f3f27b8650c3b2a82c98af997bad2bf521e9b9"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b0b42fdc4820df1d41839a249c4de6ce780e605"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "9dffc18b9152ffb83fd5e45f7ef86edceb23ab775164e0ec27ad9a088494b304"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "548eda9f5c38bf84e95012391fc21e14b2171aa8"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "d6968943ec595134f9ee480326c61632943a6c199c73977e6013384da7b691a3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c09088a16aac1bbf6dde461155db1954a563be6"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "ef5dffb2dad35ee5e68e810e0a60d6d46bdd8c69433133a453f39efd076bfb9e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "6794384309d01d424d0f897cf615b98a0ebe7d4f"
os = "freebsd"

    [[HELICS.download]]
    sha256 = "cb2492740f437303bdbf144438fd806c3b902994b25ebfe53df271920237a66c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.x86_64-unknown-freebsd.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79defa17ffa8804a4f04bc324135860bd1aa46d4"
os = "windows"

    [[HELICS.download]]
    sha256 = "a46991b85bf86c26333a8cf0c58de7d70835c8816e81f5e6415c75baae1b6157"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4175c28b3b2681668901beb3a4420665f858c3b7"
os = "windows"

    [[HELICS.download]]
    sha256 = "fd78b1a0237c110fa7594265c98be571660980ed1ceff36a68319cd24360c372"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.4.0+0/HELICS.v3.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
