[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cae4c51987163aca1022fdf547d1ef667fcc464"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "00b4c8ad184ef9275e1da4641b059511f6b83e6b3799017838df043d471f1942"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d150a84b8cacc8f591d121207a7bb9dedee3d1a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "e9c84e6f6454151edda7837f143e2b1b388d919df56c5cfac226357b0b5d1305"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13966738660ff10921728fad53b30ba80f71eb92"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "06c4e1842ba31d84e120a1cb98818abef8408c90bc72aaebe72fc13e7a7c7c9c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ee09b4d1e75a79cfbd6d0e4139d74e38f604ee1"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "da112ffc9468990eef72cdefd7741a039af59da31f2f49f8a33a890e921b5924"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c28b7a2cf06bd6a500ba6e18010e445672bc78d0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "f46f483c1e2d91ed2b4109f349d2cb48f881bf57d8c53cf212283f017e8e17f2"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe8d27090a062306bbfbc87fbbaf4b0f3080427a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "82bbf0f765b244b713c52bbad65d8a703ee8b7142e46fd4df4ff2d39f28d60b7"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d18d7bd72f555369f22e215740c0abd9773a470"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "9f9628bbaf3aa4dcbf559240da082c6545217e763fcd8c7fb8723abfe48c66f6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c00dc5f8c7a08e3696c8e1dd895082c5a47a3683"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "22115d4015f94f6d8960abe15ac3f6d056e019653f5979e084476543ded7794b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "377c8b589013adb6b5d5444e75f2a60cdc59bbf3"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "8b65904f44464d0e94bfaba793083ee84739fdf72cc26ddc036d8c006ee5e8cd"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be5d1e96581f3cad7e2d7a3dd0663f7892157c93"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "7a169ddb90b0f397069aab2501145fdfd9bf16c1b221f0db0b77867235332ead"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "beca900e9580539160ed9bda2ba3837233ba51ea"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "362feab8b1c66cf11b68d44e20fa2927de92323c080cee9eef3ee85988350f70"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83f5fe396ec070360a84e98dabe3c4fed0b9f22a"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5e40ffb8ad5203a8f2c596bace7976b2ca72ba0a9f1fe7fbb88de865065c989a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8839230501593a0964f132726e60dde851554535"
os = "windows"

    [[HELICS.download]]
    sha256 = "ffd0dc8b7bac3f67fc7cd55fdf94a94415ce78a78a758579f9c96bf375fbfc6d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77c3b9f7b1b306fd6a3b6b0339e524071cf33c42"
os = "windows"

    [[HELICS.download]]
    sha256 = "f989da6098629ad5fc8db8bc2fac38f8d7ee4a27a3abd6d15ed3a1a22ea0559b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11adbd3332ad2de17caca0aa369f7077b95d4345"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "953af58d84e3fa5747873ab29d82d5487ae3970011c2fdbef6991bb42891113c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5121907a3ab4b0a04a56d0fb8126cc226100827"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "dfb06ff1a096542a5b23112907f6d00fa7c341bd48ba5696410d06a06b1168e9"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "74b67f759b94a14e558ff743d4126b33f3df3a28"
os = "macos"

    [[HELICS.download]]
    sha256 = "5d35a16919daedcba522bd05e5da87736062ed3f9b60802dd51d3bddec551b06"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea7ac59e8a6a27ea3df14dc0561af80390d1de30"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "d6802132820024de71875ef8d65d68d538312fe070b8452e6e520851d69bf5c4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a476f013184972e56376a6180681391a30c1f152"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "cecc57b8f02cbc9a3d956d61bfc9156aee711086119d66dd0eaccc3a8c7fd87c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05088e1ab4fa8b7a49c39262e3dd7d9e63250e08"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "6fd871072dfc7009980a6baf1043128fdfd7707fa231d9f5949c92c479d478fa"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15165bac2530d50cb3d9ebde575c46ee52786634"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "e3cb72b7689e3acae515fa3a8000b8d161e9ff774cf74ae3e2e19d5659dbfb05"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a516a3772b95ac7fde52fc11515c2300e522e65"
os = "windows"

    [[HELICS.download]]
    sha256 = "06ec7bff534c227148fc6f1279eb0c546187587acb878b3aeda67f3daa43c1cd"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fd59a3ff204e6d8ca40cd4b4a80c6fc3fe9a402"
os = "windows"

    [[HELICS.download]]
    sha256 = "bb497e72def048545e5d7ea4136aeb737816770a8c8ab1f652924863c6a93ac9"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.1+0/HELICS.v2.6.1.x86_64-w64-mingw32-cxx11.tar.gz"
