[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85fe04a480820c8f3985878fab9420f777e442e3"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "21f212f79dcede18c34749ed3a6478a65d314a11d71f42f7226f4545762961f3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8042a8ad4da65fd508a5f7ddbe871113c74efccb"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "2b115c69a0b7b5c229568028a9399acde849b7c97f4d31474bf5823acfb8de6e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a3b7a8b18b25288fb77fcd0ba962ca1591266ea"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "161ef4f4c5e1874a7d0243a1bb1d589dd49cea41c7bb51d54865b1db0957c37a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37ebf5cd05872fdec2b0a73563359d98076c8f3e"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "8d4aa903e9fd6052c8c87823be8935bbca901b303ca6ca2b86e87381610b6206"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2e6867cf48d3af422aa4e194c5f57a8ce2f8d0f"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "950e63d027328b638637efc75cfaa7febf9f0148938609b4d5555dedd17c4ea0"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af2b2365dcad8788c3c9b5ac40f73167ed189563"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "b21e3882f64ffbb4e926ebc9878d6f3751d9306208f68c8b7b77a7c720c8f65d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "509b656b8ba04bdae3fff96ac12ecac686adba60"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "fad16c60fdfe967445c0491130193bc928ed1bfbda412aacc60e91b772000756"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d03674e5ac5ebe4c70f89eba3ea9addb94012e98"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "29302da3e760e2fe8a1eeea1212de7d2babdd7055b03568a1279d6d3e26dc936"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86cab8178b822cc4fff54e508f9a4b31c6790fca"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "eed9e8869622c1d0af0ab57f110dbcb1a3945f9c6bab129b9d5c6502f610fe60"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f8b758b1e7609345a61babaab76f403bd73d8b0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "4172338513325daa89b59ba37c6c667547662cbd2dcc1fcd0977f190e40b65fc"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fccfe450ce4e6f6c60bbc6ffdbd1302dd11393a9"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "b0c8fecfd342ead945732a594b635aa63d613873d1eb27944d67307a359ab548"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98656c9e7e88c59f2f097e145a0ff975f66dd87c"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5161c6a98d7c51105e5b4c0944447871d278485e6ac986a595a408f345701338"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b594f3b3f7d936e12ace6b27a57a473450b1e522"
os = "windows"

    [[HELICS.download]]
    sha256 = "d48ea46751c72e3a6ba045ae61eb57b449516f101ee914b1c16ca5228bd70c69"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50c1466f23bd20756430dc74b262aae0dcf04e5b"
os = "windows"

    [[HELICS.download]]
    sha256 = "9e107c9b0ce3aae66a073e2ac8164ec3278fa5cfb576cda509cdbc3a8206c27e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1385baa247438f6474704e749c439ca2312ec158"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "3eef002f7fbd63cf695f23e741d8010f580682c66f85417459ecd33ca14fbea8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9249b7d1f05b85ce9083af02fce12b22b756f636"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "8a03dca8e48f019075cb58c612128c3c38f19d58350605485e23e709036b3e4b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "452a62d3d4a99baafbd8c3b715de67fc7df97b2d"
os = "macos"

    [[HELICS.download]]
    sha256 = "a8ad658afcfde6cd0840bfb09ecc0806d34235122a00aa5bff32981ec76dcbd5"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf4d53e3204d88ba35467577906361d0a0da0308"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "f5989488a16ae4430af843b2a9778a928154d0ef30d2e31bde0a077bfa4fab23"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de1ea33d1365cb5099a014ccda0dcb08e02a5212"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "d2657cbb6e2473d470b241bbdd4f75718ee05e07eb230d7e93753b8b36a44e5b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad9129ad755154b5db6543d40d50c1f4fea31e9f"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "e488ecde36898174404ee4ac8f735d3775a8d1231649f2ce9afaa550011dbb30"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb425c67bd346870c2792e516d409b47c1ff1c21"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "cdac23acb9fead8c1a938a96023a1fa068ef087df5fc1ec86479fa20cdeacc6a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ba6658b24f734fae08e1a4408f52e321c3b2aa1"
os = "windows"

    [[HELICS.download]]
    sha256 = "b78c74593f6245d60c514136830f0220a940e29fb4fd9248bd4534d8aa920315"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14ca0966bdfa8ce3f6ce19beeedd6e1607c56306"
os = "windows"

    [[HELICS.download]]
    sha256 = "f5b49de6d80cb3fa8dc721eb2033f122aa3f2e605b7d445bffa9311ff0499184"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.7.0+0/HELICS.v2.7.0.x86_64-w64-mingw32-cxx11.tar.gz"
