[[HELICS]]
arch = "aarch64"
git-tree-sha1 = "8856b00d315669c8be85d623855ca3d1f3ce06e8"
os = "macos"

    [[HELICS.download]]
    sha256 = "19bce9f8bf3ab95c5a23f0c626038eece54f2e1f9256fbae7d17cc1a078b336c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.aarch64-apple-darwin.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "848f79eaeaa62d9a72ce2507ef7ebfa6c4bce9f7"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "488b2abf4b310ff8625883d2547fd0d8a8efb31123e4d9cba8562dc50f1a785b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0829f8398beefba19db41636c2829a75964ffcd0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "43260e81b690f8b26d157d8e7d1301d504a1a5f5b069ddd900dd1c490cac8e19"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dfbfcc1bea9586dab2c62d48287a32eb07d9681"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5864e2b02584efd0ac7842d40e2a3912156b0f4126b45bbe1144b9e344c0e650"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f7cb011b5507cf2b729a44c1f6d8b5da7733337"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "9d324fcf730d2085fad2592ddd17461276f14de4fe03efd959cd9f46fa746865"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0a58565dd94424c969ceae312272fd3e001f9d7"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "f9ee58527feb5d5f3f24cfc3cf896a2c5e4d1fee0b032f3adb923b457d5eaf7f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d095f40c1655f27357734e135264344cb8bf2672"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "612d55294f5ac6c2268ece10676c43289d4ecd8a3a9cbf542f8f819e03881df4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19f6f83a1b2731415fbce631a06de70bcbbde449"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "6ca017766882ba0354cab966d410d78278ff2202f0c5a4b432cc45c501c3c058"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "401e81ffb303205a53c36cdbf3f51743efd2ab13"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "ea9aaaf01b3ad63af22ea9b3b9e878468ec9f92d7eee6fa3dd9c9e838aafa0a6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af3e4afb2269dae8e800c558055d2e07f79e223e"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "77819239c3e09fef76988ec9a71d28f90aca46d57d1b299bb00855ef1ae28084"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8bb96bcc0ec86bcbee81b1ebb69d97752085b65"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "f7e3327c9eb56bf2445423a5c56090741501e624da841a6598c7c1bf892cdaf3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1179692ef94c1b7c2322390069fa49bf1625e97b"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "c0a6793ecca3415f617c55e5d8909411112eed3c2dd0c927e28ceba8549eb8af"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3b4a11bbd14f458c7e22c3021476e9de11c05c2"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "4504b2bae58c065318420587c091e6e991952f6bb6715168ddc825f78efbe584"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df18d3b40c8ad7bafb09eb539fafbef12a371512"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "5fe8e006907f5e79ae3aa2081beb47a63ca3366a9b236dd95788bccf9a7b35ca"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5688d8f99666e3506b6f5a2a7f849dcd6da25e06"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "a1220850a10f7fe4c118d90c9d35012537984052a82f79ec1bdc9d0bacae2a4c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2e452451b850d572f3601b1e68260e4b117efa2"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "1f92e1e5651e5405fd189b9be21aa33816068b6862a22d7eed24b01edff2698e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40f8bb6db5d89940170f3801ff4f21a01899fd0a"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "aab561866750ecfd7384f8b1dc40ac4080450db808f61f10abfdb977ce6771ce"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9a11f0b459099c225ab5ace045ff5037da54dd0"
os = "windows"

    [[HELICS.download]]
    sha256 = "d00065d1bc227861b147adea69457c05fcdbe0e971373313898f0ced95c1652e"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c69e8df713c11ce9a6ea8bed3b44bcb84da91f83"
os = "windows"

    [[HELICS.download]]
    sha256 = "54676c78f88b5076e33c60eae028257c737c832cba731f9587e3c815e78f10dc"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f2d40e69ebce887052919a9f2629010f58ffc1a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "1d178d67e28e7cc387253495653e98d18e008a4532f2ef989bbe061690a2b8fc"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50cf51c1d930d86979cc387720238e62ad94ea38"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "921254cee86e74eb37f40ae4596744ea316380fc5ece2a3fcfd893c6c5426a85"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "d7543ef25374b2b36c1077d0b922d4ec5f91f12b"
os = "macos"

    [[HELICS.download]]
    sha256 = "dafd9a6c8d822bc3c1a02d4780e05be236659698679c81b710948f009dfb5dde"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f933ec593a0099a3dc589147d74d4bcdb5c2dcaf"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "11509517410aeb33baea36fc93284cd3551d969fc514006ad86dfa713943e624"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f8cf89640febcad375f9d1a949345718ff8003e"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "a8d52450e21f09136326bc77e43d899f45bcf34cce6a87a6aeefd79c4139d0d3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "542f0cf0c65b3a6def1cd631bcdab5c798d8f071"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "d2b4da942b18764960513ac4a9ce480b6bbb227324c66f58566f6f50255afec4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8319650cec747441885ab4de81f5613d02aa9d97"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a235cbdc5598bbe11e78e9de3780e770aefd603edf6041d48ae9d28f36ba8fb7"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "d6a59136298b8f9939140ce7b81146a7e85b0bb8"
os = "freebsd"

    [[HELICS.download]]
    sha256 = "4a5e4449ac1a5e9422ff15dda4f58c33e6ad18ce31db09af308d8ad35d4c3280"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.x86_64-unknown-freebsd.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a09a8cc8bd4437154ab400eaaabacc3e088e0c9"
os = "windows"

    [[HELICS.download]]
    sha256 = "3ba605eba89a4caba6ffe122ceeff2b6ba4dab85196b81c3c73a74b50e41e93c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f56e7e67fd6432f92a46ccfed071ab490f0f4ec"
os = "windows"

    [[HELICS.download]]
    sha256 = "788a1d74b5b5701638adff41e6f54d4df1b06e2bd4a9f779a8cc7c7d5ed910a6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.5.3+0/HELICS.v3.5.3.x86_64-w64-mingw32-cxx11.tar.gz"
