[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03f7d6f0c535866830fb2efe29994bb2c0489aeb"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "bad56bbdd24cdd4231660e873a4b545d1a94174f98d9454e12e9e1e5dadd23d2"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd819a56dc7838b321daeabc5ecc2908711b8738"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "2ea67799c7a4b6c4807d522d00b5f388c2187f7d24eea4cf0fa6e6215ca5324d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5346af65ac8bb61943ae0167b9c28c5c4e05ac6f"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "b9676a0bd25e5503601bd27eeb12eacd626c2bae6e4921f50cb0b9e1578b340b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a75a0a33f01c78e1d189b752e906bf2d70f951e2"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "8460163a485e2e557cae7733d6fda11745e8e22c7a6e7b20327c20ac6797d1a2"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "970121a1898595bbc6f7622ae1866b0f5775cd94"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "b8bc042665b1c7d84833ff60ab89278032f28d2e2b3737397d0597f61104a1ad"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92901d777b526a3f4bd8bcb58e0c8f640364b224"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "32cd5e1cf06ff3f721ef189a9f4f0444bd088c43d18dfae4835e1bb8050165bc"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d83aadd58fe3fe186359329c006cfcdaef5e23fb"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "0ffbd5c59f4749b1651fde2342cdc9f380984712cc42c8e8e933df6ac67fdca9"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d27b02700c846ba046ead5556b305cafa170e561"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "034a124d73534a92b35b501f560bb46cb790e160164609845fe23396de0d5868"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3e5559468130264b666bf1ea7ab45a23e21e984"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "82ca3d2dcad11207d43bc0f7d712b904f80903884e82bcfcbb8fd98ddb583562"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "014c55a546f2392639c28f533b6e0328a930698a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "1b6a50c5dd95616432a5d9df08ce884f9579523dd469081011ac6eef0d3ecb30"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e281b2ad0bf99c2c5565da70b82722bb3d8c09c1"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "3eb0be4c73986d46d9e21450a8320ff1bc11155089d854df84f79c3b3c02e5c6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94f2dba37bf244460e2539381fe271880eff743a"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "1adc28887847f5988e50ff76ca1de72b645159254d02ac0aeeb39dcc0eb495b4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8bacda115efe8b8e314fc41a1303e41dba350e2f"
os = "windows"

    [[HELICS.download]]
    sha256 = "667fbf84e821ee118ab514506a6b4ba1d3d2e85415afa3d7a639c218ddba2d34"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6a3ec183b5261dcac9b11ca956174728219d2ef"
os = "windows"

    [[HELICS.download]]
    sha256 = "a22547874002d20d65a614dd593d5824c4923c9ce0e77bf0c3ed7b3e76515d73"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "119e0b59fd5bd50d84093a6a0940daea993ac795"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "0c16f1f12ed5e566bdec8c406574a96c12f0e3cf724dd07760ec3e8c95f4b2f1"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fb18d00e6b191142ddc471eefffd4aa16383517"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "2f5a21603416788307adeb23944508fdc0411903922acb5215163164293f69e4"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f51b094d1df4b23b0fac4f07ed8606b4cb1942dc"
os = "macos"

    [[HELICS.download]]
    sha256 = "cd2c49fabf1b929199b31f61c7fe55dbdff928a84a9bd85afbf78c595eaa5db6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "445f563a17ff3e39875aa6faeb1299fef8baf8b2"
os = "macos"

    [[HELICS.download]]
    sha256 = "3b2331d2e52163da8be3b175117e51b419d2c0b9201d61473d0e75fe7eed7c61"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d868343b5a379ac06d7e503bd9eb9cd570577ebd"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "fae251261ac33c37faf591b3c09bc61ec69f118dfb0826bdb77a55ec806f97f8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35a0b3f423366ec66ecd8a487e79e073e7829b36"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c91ec32d2e510d7a547ff58d045815b08aad9c17c64b4203054b2be04de06d42"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5705b0fc7103797352249206f73745ec6e61253"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "fa75d2f5b08d19810d0f17fdc0465e9261ab6418f452a77d1bfa7b1e30600574"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a04a22c26d5f9128c31df3f765cd1ba8979817b"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "424eb9d44f2a838d107935ec6fb4b02f353020bceec627123aafc0f5c1e71b3c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5526f61613fff46e37109714d07a547ab56b8e8b"
os = "windows"

    [[HELICS.download]]
    sha256 = "dcdd0f00d74f1193cbacd3782e0fa4769244fb612e5f01af692bf43399e677bb"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe3ac3289192ad1b83e97ef0a2eb3e26106c227a"
os = "windows"

    [[HELICS.download]]
    sha256 = "6970b12bde10b24d6421cca90dfbb34fb41b8674a7cbc4077f4fe07d476f73f0"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.6.0+0/HELICS.v2.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
