[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce2dfb907b5f3be719f93439dd66e4a756490364"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "2915decec291f24472179c4a5adc25aa57141cb9cd624f1c075074c4711dd0b3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a85d4468e58db3b248f63c7841857278445c354"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "9b5a3530b9510c9fe5a6c33715baf32e1199a2769986c73af4c5f0ee699e7daf"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0528d8e1467b69790e8a20bd3a5029de75cfd89"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "a7a2628bc22c0491d1aea2074546f8fd7f5b7bf905db5028ae4dc0c6c1e90d13"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae10d25594e1094a3348b9897939a77c3c16b17d"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "5fd84282c1f7e4eec97ba5d6b552abc8b874174454c611ff37ed7dc2f673a6a8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "974ce5b4baa7eb3c99037c84ada17d3bce70fa8c"
os = "macos"

    [[HELICS.download]]
    sha256 = "16b34bd8d379a9b74ac927ef6bf4936a661a50924fb9d055f3d1ede589c44e18"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d56f8d63b909cbac20e865e421e6f05121f3fff7"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "b9ba2e0a49ed5f3cf1a305b3fc1224c6a114502e70272e93bea1aa569a21f6ad"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1d031e0adca3b9cd5cfdbb671fb02e9ccc19bfb"
os = "windows"

    [[HELICS.download]]
    sha256 = "3888705270b7b57423def39a515e6fd58696f315a0655dcc9f91a0a46da3ba14"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb3eaf18a7efa551158b33d33007cb5b44b53c9d"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "55b3795d0b5730f0d8d085120157087df77a7497f06889ef4559fdefde06be33"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38da28f0104c4065013518c6dc318bdd6a1aa159"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "8af071c4263a69c29f1753d150080a0b85aff9a3200bfca648e2133ea511110c"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca410f9b81ae08a0923a564f5045fb846761bbaa"
os = "macos"

    [[HELICS.download]]
    sha256 = "194d77e0d2014784d90e940c34c7ebcc8f8b7c192c8d994bdb077a1be371ea4a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63cc1ed477390a3324431f4a7345cbc053b736a5"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "ae0d5479a56ae7ee2ed23db5568ff6e622c75a5c8674f6cec578624d75fa9c75"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3de874486e91b01d67a86d5daa2c1f5f2a43109"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "843cf194de293e1d35a5ce7f8e4c758daf6de05dfbf3ab4e94a2bd09f12581de"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e6253346e4a34481a7b39928995c15a597ae483"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "2ea8f563cd1d0088cdada35cba5072c661086155d97b34f31c2764d427f8fa0f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "962e67d1d2330b3a2e8e393047fc6d022e387edb"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "6c0debabab33cb509bad0da052ba544d1029dba27b5e0351e0fb5acbd74a221a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fd4073b1202a4d33178f3fb7c487a557f756540"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "94cb76ec75ab4e54b53755e3bb60cd20ebd7d82c36535710200df7e6a46f9c41"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "172e3155afa9b12f499104225bf1a65588d26677"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "a855fa32989f8e5ac7cd9f9f8338105e05837c3a669cbc117fce545d362b7b35"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fa5d2bd27181d991cf9a4fa0620450ec6082a69"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "5f2e0801a86966e3ed56783442cdd1a8af5ece1f30cb2f024d76682b3966cffb"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06ef44eb750653e80e529959d77feb4f083f9ae5"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "f8178ceff23d7dfb5ce3308abd9e9b0e564f1b4f372775f06dac7ebc6e503f68"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "555f033b51ee2d6dcf0bf3d4f788f0c8cb778b20"
os = "windows"

    [[HELICS.download]]
    sha256 = "730aaf349f67ac4939eb754bff4ad63ad95703490fcec26f5e4155ffe4028218"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "096017c0939af4e983f984a75db0ca623640e2f0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "b7405f9760a61384204d98a6106422af8f20c1f2719a1c29654fb521ee48f3a5"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac7ca6650301e0ea82e5f8d00dca1c642224e623"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "1f025ce5d245dbb4beaad614fb85112ac4e7c967b7cb60ade89468073074234f"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3e5cac6538536c08c25f546fcfe1f0e470abb1a"
os = "windows"

    [[HELICS.download]]
    sha256 = "ce2e14fdb61560d4c766fe2271b035cf08d8d4c22a5dcf687375dab95f2428c2"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7669eddf42e595e114ec5bc621e5fd51a0492e3e"
os = "windows"

    [[HELICS.download]]
    sha256 = "85438ac6c108b0d22d4ad9139907a558757fdd68b65664f9ad4fb8992f2e530b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7e164ff97ba0e36326dc3aedb0ab7b349c2696b"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "bda6e1b69a4949096bd78d3e76f846c73c28fc5f1e77cd9416d7cefc509fa796"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v2.4.0+0/HELICS.v2.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
