[[HELICS]]
arch = "aarch64"
git-tree-sha1 = "47ed5731e7e64e9eb8bb3ba2ca87697e3a4336f0"
os = "macos"

    [[HELICS.download]]
    sha256 = "9bed1a61e4e2b53a95f2d6c11eafc10ecace17da20bd8c65f553b451025960cd"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.aarch64-apple-darwin.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1d12b12392889fad5da94d5c6276bc367a74c5f"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "42bf332c7bae8a36de9fa2136a507c02a86513961279862a059f2916fe2632f8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e5b29dba172ec140545db972a2390cb205f3879"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "5679166c827e31329468fb1f90e31200d950cd15531aa3c1e75600f4dc8e5686"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9afe02f336d85673ee4e7514281e16152757fbe6"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "bac5884363f621718381d6d0ddd740261822cbb4ba117426097f742e059520b1"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.aarch64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ec56b960d05c6ee7d3d83cd08fb0370f72e5315"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "df4c0b748353d7fb008ba5556297d97dbbe3c4b53e87411d393070636db916bf"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.aarch64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "aarch64"
git-tree-sha1 = "af5d5b88f8d794b7c0739f25b0ea0cb33da9a222"
os = "freebsd"

    [[HELICS.download]]
    sha256 = "cb2a863481993a2e8f23d783523f374a9c37c597646cf3728f1145a7e76edd9d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.aarch64-unknown-freebsd.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15fcc4dd9d64fe2fff72e3fe3c8f6dd4c67c10fe"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "3f15eb6f58dcad197a0cb813b8903bfb04254689251d82e6d74da2b8ac58af2b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7961bf70412bdc72be13c330fa62a8665aabc1a5"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "9dfaeabc7f5548b090aa260930c21e3fafc40888afe7591068d0eba03818d056"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "832b1f6d0e4982913befa773c47019b1bad3be75"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "17ab7efd6b0aa0ea404480b0a7267657aca046ea345571ef5086965c9bf31737"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce07ac0916532e4810bc86be39aa1b487978d8dc"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "be6726a5426252f644bebaca44ff0f2312adb98e4bb35e6bc9afded4943a7d1b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "daa7906ea1831e28c4142c8e3d6fc45c78fd9c88"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "5748d859b121201d9b425c5837ddaaca172e2c3556def5d32ffc38f094254b72"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ace4f9e3821b46ddad26794e03708593455dde4"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "66940eff3f661180f6819f70e5f9362c7cd6043887f832f06a5a09ef7551af56"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d2cb9e4302dcff69893bb418da4afc144fb2958"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "d240f8d668c556363d1cdd73801dfacac068fea5fc51218f054e4d8910e65c14"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HELICS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10d2433feef50cdb2e1f63300d4219dca020d45d"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "b7acd67f41cab229e40a4e8edffa61218b24e62924e93499e7a50038c0bf1308"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "552ac6d26359966dade089a6659b3b30b84b6c95"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "034e44088481071db69bd5e7af02d50986537ec1e43901f37cc67220b7c944d1"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.i686-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52cfc36c920a5317774aa66351949b431152bf69"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "9ccc72c47a918afca2c82443fb4b2271cdf0731ed1ab05566ab92027a33db386"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.i686-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0d88b06035f1b4bc36885715d3f7214daf518ee"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "d450bd2006ddaa5d9cc0e78bb080be28e5df8fd7a3e3393af3dc6e6d23b9eba6"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.i686-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93ff8425f5e919766b7da7a2582fa93e0d6cb632"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "c9d55988c2296a9c24efd6fb5cf73a30d4f0606f63ff3c1274061bbb428f65b3"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.i686-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cf56debfda147a560a89a54e8f35f86648e7dc4"
os = "windows"

    [[HELICS.download]]
    sha256 = "09b9b83c02bda047ade90f813c51ea7bb85a9fcbec05df97ccb72474ae3a8eeb"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.i686-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb43a84e4c7321cea1198691767590f003db05ab"
os = "windows"

    [[HELICS.download]]
    sha256 = "8881c77de1e494731a221f04139fe62506eab827e6c509470fd36c8321ec2d0a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.i686-w64-mingw32-cxx11.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4eeae289f6a7b855964c2eedfd4156518e9201e0"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "83678cfb852089f380930d1c6badf61b12ba6195e54e61814eae4652fabbb54d"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8052116a5adbfd0eb01e782ed6ed0e32bf4c25b"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "0ad0acdb4d9f0034559fd8fca96a603ef3474759ca9e8a30f5c3b618c466cdad"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "991f5a1d1ed337369b0231793d5dc5f4ef9e6360"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "553b7560f71822ae1d61b50fa7277deed385c233cdb5065329d81599804d408a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.riscv64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59665493b7249762092255025d446079a4254e70"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "c26ba05859949682d17550835d4a30b31de2983742bd5fcc61d24eccc93343ad"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.riscv64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "8bce271c03c3affaf310732f3b82870f07f9969a"
os = "macos"

    [[HELICS.download]]
    sha256 = "ffeedad90ebf3f46b2e3501ebab47b20c6f1562bebebc62cab23bc01afdc4ed8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.x86_64-apple-darwin.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5538e661ff901f25d4cb462e90cb198b4e07a35a"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "ad0cecd371ef1e921a85c605a3495d21c4cde54615d809cfef87d6be3c476ffe"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4c99d75ca9f518a0d75bf09b4616766c86ae66d"
libc = "glibc"
os = "linux"

    [[HELICS.download]]
    sha256 = "afcfc3f1de50b8778988b179c0d18172261b0b7cd60f11b83a5cf090f41b5768"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e3bb1d718dd79a5f9dfa41673dbebc96976a073"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "8432cf962fc74cf05e9fb6fc063e799e479968015e3fe167b335e00f0a9f6ca8"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.x86_64-linux-musl-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd819d940c68e9b2e3d438f4cd1f6595c2bffdbd"
libc = "musl"
os = "linux"

    [[HELICS.download]]
    sha256 = "33c2a12538afb3f5b441757b95b81935a0d4a8960a4e9a70b809e4fbe7b01393"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.x86_64-linux-musl-cxx11.tar.gz"
[[HELICS]]
arch = "x86_64"
git-tree-sha1 = "df225057febeabb5ccb8fe021318a5da04d73538"
os = "freebsd"

    [[HELICS.download]]
    sha256 = "314c4892f441190f9981ee3470e4d6e2aefbb7a36d77b378843be33c7857f50b"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.x86_64-unknown-freebsd.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b184bbdd17f2a2c1c8a65b4d4eb91193a64d872b"
os = "windows"

    [[HELICS.download]]
    sha256 = "3fd5d755eb56927db4c273253a7d94424e5fd85eb8e87771b603367156e1494a"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[HELICS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d456c73bd8d761a6f5c58a968b8482601f98100"
os = "windows"

    [[HELICS.download]]
    sha256 = "6791a455f09e5062140b6254c979e0de262f301d075455205d84e669bd7c7236"
    url = "https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/download/HELICS-v3.6.1+0/HELICS.v3.6.1.x86_64-w64-mingw32-cxx11.tar.gz"
